# Generated by Django 3.2.16 on 2023-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFFRONTENDDJ', '0003_remove_finda_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('Day', models.CharField(max_length=256)),
                ('Time', models.CharField(max_length=256)),
            ],
        ),
    ]
