# Generated by Django 3.2.16 on 2023-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFFRONTENDDJ', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
